# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.51.0"
StyLua = "JohnnyMorganz/StyLua@2.1.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
lune = "lune-org/lune@0.9.4"
rojo = "rojo-rbx/rojo@7.5.1"
selene = "Kampfkarren/selene@0.28.0"
wally = "UpliftGames/wally@0.3.2"
