# This config exists so we can import the dependencies of all packages for analysis.
# THIS PACKAGE IS NOT DIRECTLY PUBLISHED!

[package]
name = "neura-studios/sentry-lua"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.3"
RegExp = "jsdotlua/regex@1.0.2"
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
