-- based on: https://github.com/getsentry/sentry-javascript/blob/540adac9ec81803f86a3a7f5b34ebbc1ad2a8d23/packages/browser/src/stack-parsers.ts

local PackageRoot = script.Parent
local Packages = PackageRoot.Parent

local LuauPolyfill = require(Packages.LuauPolyfill)
local String = LuauPolyfill.String

local Types = require(Packages.SentryTypes)
type StackFrame = Types.StackFrame
type StackLineParser = Types.StackLineParser
type StackLineParserFn = Types.StackLineParserFn

local Utils = require(Packages.SentryUtils)
local createStackParser = Utils.createStackParser
local logger = Utils.logger

local Client = require(PackageRoot.client)
type RobloxOptions = Client.RobloxOptions

local ClientTypes = require(PackageRoot.types)
type SourcemapEntry = ClientTypes.SourcemapEntry

--- Maps a DataModel path back to the filesystem using a Rojo sourcemap file, if provided. For example, this can turn:
---  - `ReplicatedStorage.Shared.SomeFolder.SomeModule` -> `src/shared/SomeFolder/SomeModule.lua`
---
--- This process is crucial for getting source code alongside stack traces within the Sentry UI.
---
--- @param dmPath Path to an instance on the datamodel (e.g. `ReplicatedStorage.Foo.Bar`). Can be retrieved with `Instance:GetFullName()`.
--- @param sourcemap Sourcemap entry generated by Rojo.
--- @return The corresponding file path of the provided instance, or the original instance path if no file could be found.
local function resolveSourcemapPath(dmPath: string, sourcemap: SourcemapEntry): string
    local previousNode: SourcemapEntry?
    local currentPath = dmPath

    local function visitSourcemapNode(node: SourcemapEntry)
        local nextSegment = string.split(currentPath, ".")[1]
        if nextSegment and String.startsWith(node.name, nextSegment) then
            previousNode = node

            currentPath = String.slice(currentPath, #node.name + 1)
            if String.startsWith(currentPath, ".") then
                currentPath = String.slice(currentPath, 2)
            end

            if currentPath == "" then
                return
            end

            if node.children then
                for _, child in node.children do
                    if currentPath == "" then
                        break
                    end
                    visitSourcemapNode(child)
                end
            end
        end
    end

    if sourcemap.children then
        for _, child in sourcemap.children do
            visitSourcemapNode(child)
            if currentPath == "" then
                break
            end
        end
    end

    if previousNode == nil then
        if _G.__SENTRY_DEV__ then
            logger.warn(`Failed to resolve sourcemap path for instance ({dmPath}): sourcemap does not contain instance`)
        end
        return dmPath
    end

    if not String.endsWith(dmPath, previousNode.name) then
        if _G.__SENTRY_DEV__ then
            logger.warn(`Failed to resolve sourcemap path for instance ({dmPath}): sourcemap does not contain instance`)
        end
        return dmPath
    end

    local filePaths = previousNode.filePaths
    if not filePaths or #filePaths == 0 then
        if _G.__SENTRY_DEV__ then
            logger.warn(`Failed to resolve sourcemap path for instance ({dmPath}): sourcemap node has no file paths`)
        end
        return dmPath
    end

    return filePaths[1] or dmPath
end

local function createRobloxStackParser(options: RobloxOptions)
    local robloxParser: StackLineParserFn = function(line)
        local path, lineNumber, functionName

        -- note: These pattern matches are based on another Sentry SDK for Roblox
        -- https://github.com/devSparkle/sentry-roblox/blob/429eda39bcfddc3d6065b9744193613b34fce067/src/Integrations/StackProcessor.lua#L32-L56
        if string.find(line, "^Script ") then
            path, lineNumber, functionName = string.match(line, "^Script '(.-)', Line (%d+)%s?%-?%s?(.*)$")
        elseif string.find(line, ", line") then
            path, lineNumber, functionName = string.match(line, "^(.-), line (%d+)%s?%-?%s?(.*)$")
        else
            path, lineNumber, functionName = string.match(line, "^(.-):(%d+)%s?%-?%s?(.*)$")
        end

        if functionName then
            functionName = string.gsub(functionName, "function ", "")
        end

        local sourcemap = options.projectSourcemap
        if path and sourcemap then
            path = resolveSourcemapPath(path, sourcemap)
        end

        return {
            filename = path,
            function_ = functionName,
            lineno = tonumber(lineNumber),
            in_app = true, -- All Roblox frames are considered in_app by default
        }
    end

    local robloxStackLineParser: StackLineParser = {
        priority = 100,
        parser = robloxParser,
    }

    return {
        robloxStackLineParser = robloxStackLineParser,
        defaultStackParser = createStackParser(robloxStackLineParser),
    }
end

return createRobloxStackParser
